-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  unit text not null,
  category text not null,
  image text,
  rating numeric default 0,
  reviews integer default 0,
  in_stock boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Orders Table
create table orders (
  id text primary key,
  user_id uuid references auth.users not null,
  items jsonb not null,
  total numeric not null,
  status text default 'Processing',
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  address text not null,
  payment_method text not null
);

-- Create Profiles Table (to store extra user data)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  phone text,
  role text default 'FARMER',
  full_name text,
  updated_at timestamp with time zone
);

-- Set up Row Level Security (RLS)
alter table products enable row level security;
alter table orders enable row level security;
alter table profiles enable row level security;

-- Policies for Products
create policy "Public products are viewable by everyone."
  on products for select
  using ( true );

-- Policies for Orders
create policy "Users can view their own orders."
  on orders for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own orders."
  on orders for insert
  with check ( auth.uid() = user_id );

-- Policies for Profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, phone, full_name)
  values (new.id, new.phone, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
